# headers and icon 
title: Hannah Estes
info: PhD CS @ NC State
url: https://hannahestes.github.io  # used for link previews
icon-pic: assets/img/comic_portrait_icon.png

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
